# Generated by Django 6.0.6 on 2026-06-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Lapangan')),
                ('sport_type', models.CharField(choices=[('BADMINTON', 'Badminton'), ('VOLI', 'Voli'), ('FUTSAL', 'Futsal'), ('MINI_SOCCER', 'Mini Soccer'), ('BASKET', 'Basket')], max_length=20, verbose_name='Jenis Olahraga')),
                ('capacity', models.IntegerField(verbose_name='Kapasitas Orang')),
                ('price_weekday', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif Weekday (/jam)')),
                ('price_weekend', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarif Weekend (/jam)')),
                ('image', models.ImageField(upload_to='fields/', verbose_name='Foto Lapangan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
            ],
        ),
    ]
