# Generated by Django 6.0.6 on 2026-06-07 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Tanggal Main')),
                ('start_time', models.TimeField(verbose_name='Jam Mulai')),
                ('end_time', models.TimeField(verbose_name='Jam Selesai')),
                ('participants_count', models.IntegerField(verbose_name='Jumlah Orang')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Biaya')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Menunggu Pembayaran)'), ('WAITING_CONFIRMATION', 'Menunggu Konfirmasi Admin'), ('CONFIRMED', 'Dikonfirmasi'), ('PAYMENT_REJECTED', 'Pembayaran Ditolak'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=25, verbose_name='Status Reservasi')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Bukti Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fields.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
