# Generated by Django 6.0.6 on 2026-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Batas Waktu Pembayaran'),
        ),
    ]
